### ISSUE TITLE
Proposal: Syntax for recurrent phrases

### ISSUE THREAD

**Issue by benchristel** [gavmor/Dunmanifestin#11]
## Why

We're currently feeling a need to have phrases recur more often than they do by random chance. Recurrence would be useful because it would let us generate worlds with characters and places that reappear over and over, rather than being mentioned only once.

## Syntax

I propose the following two-part syntax to allow users to define the "population" of a palette.

### Population number in palette definition:

```
|character*20
[name.capitalize] the [epithet.capitalize]
```

Used by itself, this syntax would have no effect on the generated output. But it would govern the probability with which `characters` would recur, when referenced with the syntax below....

### Recurrence markers in variables

```
|gossip
[recur:character] likes [recur:character]!
```

Here, `recur:` says explicitly that we want characters we've seen before to be reused. It's necessary to have this syntax because if we apply recurrence blindly, we'll end up generating identical characters when we want to have unique ones.

What `*20` means in the `character*20` definition is that when we generate a `recur:character`, the probability of using someone we've seen before will be `POP / (POP + 20)`, where `POP` is the population of characters that currently exist. If we'd chosen a number larger than 20, the world would seem bigger (because characters would recur less often), and if we'd chosen a smaller number, the world would seem smaller.

@gavmor what do you think? Does this seem okay, at least in outline?

**Comment by gavmor** [comment]
I am definitely impressed with the idea of introducing palette syntax for
this, rather than the global CLI flags I was considering—and the somewhat
confusing notion of two seeds and semi-randomness that I implemented last
week.

—
Gavin

**Comment by benchristel** [comment]
IT IS DONE.
